# Generated by Django 4.1.3 on 2022-12-27 03:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(default='location', max_length=200)),
                ('max_player_num', models.IntegerField(blank=True, null=True)),
                ('team_num', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('visible_to_everyone', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'soccer_team_game',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_member_num', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'soccer_team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoccerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='[0-9]{10}')])),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soccer_custom_user',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'group'), ('game', 'game')], default='group', max_length=5)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.game')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.socceruser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.socceruser')),
            ],
            options={
                'db_table': 'soccer_team_admin',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='soccer.socceruser'),
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.game')),
                ('players', models.ManyToManyField(to='soccer.socceruser')),
            ],
            options={
                'db_table': 'soccer_game_team',
                'ordering': ['game'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='organizers',
            field=models.ManyToManyField(to='soccer.socceruser'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.group'),
        ),
    ]
