# Generated by Django 4.1.3 on 2022-12-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupadmin',
            old_name='team',
            new_name='group',
        ),
        migrations.AlterModelTable(
            name='groupadmin',
            table='soccer_group_admin',
        ),
    ]
