# Generated by Django 4.1.3 on 2022-11-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(default='location', max_length=200),
        ),
    ]
