# Generated by Django 4.1.3 on 2022-12-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_rename_team_groupadmin_group_alter_groupadmin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='socceruser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
