# Generated by Django 4.1.3 on 2022-12-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_socceruser_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socceruser',
            name='confirmation_code',
        ),
    ]
