# Generated by Django 4.1.3 on 2022-12-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0007_alter_game_team_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
    ]
