# Generated by Django 4.1.3 on 2022-12-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0008_alter_game_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'group'), ('game', 'game')], default='group', max_length=5)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.game')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.user')),
            ],
        ),
    ]
