# Generated by Django 4.1.3 on 2022-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0009_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
